phoenix:
  name: phoenix
  image: birdhouse/pyramid-phoenix
  imagePullPolicy: IfNotPresent
  replicas: 1
  ports:
    http: 8081
    https: 8443
    output: 8000
  hostname: phoenix.192.168.99.103.nip.io
  mongodb:
    name: mongodb
    port: 27017
    image: mongo:2.6.12
    imagePullPolicy: IfNotPresent
  resources: 
    requests:
      #Minimum CPU and RAM requirements (must be set if HPA is enabled)
      memory: 1Gi
      cpu: 400m
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 8
    #CPU and RAM triggers for autoscaling, as percentage of {{ .Values.tds.resources.requests }}
    cpuUtilization: 80
    memUtilization: 100


emu:
  enabled: true
  name: emu
  image: birdhouse/emu
  imagePullPolicy: IfNotPresent
  replicas: 1
  hostname: emu.192.168.99.103.nip.io
  port: 5000
  logLevel: WARNING

hummingbird:
  enabled: true
  name: hummingbird
  image: birdhouse/hummingbird
  imagePullPolicy: IfNotPresent
  replicas: 1
  hostname: hummingbird.192.168.99.103.nip.io
  port: 5000
  logLevel: WARNING

flyingpigeon:
  enabled: true
  name: flyingpigeon
  image: birdhouse/flyingpigeon
  imagePullPolicy: IfNotPresent
  replicas: 1
  hostname: flyingpigeon.192.168.99.103.nip.io
  port: 8039
  logLevel: WARNING
