{{- if .Values.emu.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.emu.name }}-custom-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "default-labels" . | indent 4 }}
    component: emu
data:
  demo.cfg: |-
    [server]
    url = http://{{ .Values.emu.name }}.{{ .Release.Namespace }}:{{ .Values.emu.port }}/wps
    outputurl = http://{{ .Values.emu.hostname }}/outputs

    [logging]
    level = {{ .Values.emu.logLevel }}
{{- end }}
