apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pyramid-phoenix
  namespace: birdhouse
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: phoenix
spec:
  rules:
  - host: {{ .Values.phoenix.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.phoenix.name }}
          servicePort: {{ .Values.phoenix.ports.https }}
  tls:
    - hosts:
      - {{ .Values.phoenix.hostname }}
