{{- if .Values.hummingbird.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hummingbird.name }}-custom-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "default-labels" . | indent 4 }}
    component: hummingbird
data:
  demo.cfg: |-
    [server]
    url = http://{{ .Values.hummingbird.name }}.{{ .Release.Namespace }}:{{ .Values.hummingbird.port }}/wps
    outputurl = http://{{ .Values.hummingbird.hostname }}/outputs

    [logging]
    level = {{ .Values.hummingbird.logLevel }}
{{- end }}    
